# Use the official Python image as the base
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the application port
EXPOSE 8080

# Run the init.sh script
RUN chmod +x /app/init.sh
CMD ["/bin/bash", "-c", "/app/init.sh && uvicorn app:app --host 0.0.0.0 --port 8080"]
